import { ActionConstants } from "./redux/actionConstants";

export const hand = {
  "A-10": {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.STAY,
    8: ActionConstants.STAY,
    9: ActionConstants.STAY,
    10: ActionConstants.STAY,
    A: ActionConstants.STAY,
  },
  "A-9": {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.STAY,
    8: ActionConstants.STAY,
    9: ActionConstants.STAY,
    10: ActionConstants.STAY,
    A: ActionConstants.STAY,
  },
  "A-8": {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.STAY,
    8: ActionConstants.STAY,
    9: ActionConstants.STAY,
    10: ActionConstants.STAY,
    A: ActionConstants.STAY,
  },
  "A-7": {
    2: ActionConstants.STAY,
    3: ActionConstants.DOUBLE_DOWN,
    4: ActionConstants.DOUBLE_DOWN,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.STAY,
    8: ActionConstants.STAY,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "A-6": {
    2: ActionConstants.HIT,
    3: ActionConstants.DOUBLE_DOWN,
    4: ActionConstants.DOUBLE_DOWN,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "A-5": {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.DOUBLE_DOWN,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "A-4": {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.DOUBLE_DOWN,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "A-3": {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.HIT,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "A-2": {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.HIT,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "A-A": {
    2: ActionConstants.SPLIT,
    3: ActionConstants.SPLIT,
    4: ActionConstants.SPLIT,
    5: ActionConstants.SPLIT,
    6: ActionConstants.SPLIT,
    7: ActionConstants.SPLIT,
    8: ActionConstants.SPLIT,
    9: ActionConstants.SPLIT,
    10: ActionConstants.SPLIT,
    A: ActionConstants.SPLIT,
  },
  "8-8": {
    2: ActionConstants.SPLIT,
    3: ActionConstants.SPLIT,
    4: ActionConstants.SPLIT,
    5: ActionConstants.SPLIT,
    6: ActionConstants.SPLIT,
    7: ActionConstants.SPLIT,
    8: ActionConstants.SPLIT,
    9: ActionConstants.SPLIT,
    10: ActionConstants.SPLIT,
    A: ActionConstants.SPLIT,
  },
  "9-9": {
    2: ActionConstants.SPLIT,
    3: ActionConstants.SPLIT,
    4: ActionConstants.SPLIT,
    5: ActionConstants.SPLIT,
    6: ActionConstants.SPLIT,
    7: ActionConstants.STAY,
    8: ActionConstants.SPLIT,
    9: ActionConstants.SPLIT,
    10: ActionConstants.STAY,
    A: ActionConstants.STAY,
  },
  "7-7": {
    2: ActionConstants.SPLIT,
    3: ActionConstants.SPLIT,
    4: ActionConstants.SPLIT,
    5: ActionConstants.SPLIT,
    6: ActionConstants.SPLIT,
    7: ActionConstants.SPLIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "6-6": {
    2: ActionConstants.SPLIT,
    3: ActionConstants.SPLIT,
    4: ActionConstants.SPLIT,
    5: ActionConstants.SPLIT,
    6: ActionConstants.SPLIT,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "5-5": {
    2: ActionConstants.DOUBLE_DOWN,
    3: ActionConstants.DOUBLE_DOWN,
    4: ActionConstants.DOUBLE_DOWN,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.DOUBLE_DOWN,
    8: ActionConstants.DOUBLE_DOWN,
    9: ActionConstants.DOUBLE_DOWN,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "4-4": {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.HIT,
    5: ActionConstants.SPLIT,
    6: ActionConstants.SPLIT,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "3-3": {
    2: ActionConstants.SPLIT,
    3: ActionConstants.SPLIT,
    4: ActionConstants.SPLIT,
    5: ActionConstants.SPLIT,
    6: ActionConstants.SPLIT,
    7: ActionConstants.SPLIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  "2-2": {
    2: ActionConstants.SPLIT,
    3: ActionConstants.SPLIT,
    4: ActionConstants.SPLIT,
    5: ActionConstants.SPLIT,
    6: ActionConstants.SPLIT,
    7: ActionConstants.SPLIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
};

export const count = {
  20: {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.STAY,
    8: ActionConstants.STAY,
    9: ActionConstants.STAY,
    10: ActionConstants.STAY,
    A: ActionConstants.STAY,
  },
  19: {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.STAY,
    8: ActionConstants.STAY,
    9: ActionConstants.STAY,
    10: ActionConstants.STAY,
    A: ActionConstants.STAY,
  },
  18: {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.STAY,
    8: ActionConstants.STAY,
    9: ActionConstants.STAY,
    10: ActionConstants.STAY,
    A: ActionConstants.STAY,
  },
  17: {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.STAY,
    8: ActionConstants.STAY,
    9: ActionConstants.STAY,
    10: ActionConstants.STAY,
    A: ActionConstants.STAY,
  },
  16: {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  15: {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  14: {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  13: {
    2: ActionConstants.STAY,
    3: ActionConstants.STAY,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  12: {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.STAY,
    5: ActionConstants.STAY,
    6: ActionConstants.STAY,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  11: {
    2: ActionConstants.DOUBLE_DOWN,
    3: ActionConstants.DOUBLE_DOWN,
    4: ActionConstants.DOUBLE_DOWN,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.DOUBLE_DOWN,
    8: ActionConstants.DOUBLE_DOWN,
    9: ActionConstants.DOUBLE_DOWN,
    10: ActionConstants.DOUBLE_DOWN,
    A: ActionConstants.HIT,
  },
  10: {
    2: ActionConstants.DOUBLE_DOWN,
    3: ActionConstants.DOUBLE_DOWN,
    4: ActionConstants.DOUBLE_DOWN,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.DOUBLE_DOWN,
    8: ActionConstants.DOUBLE_DOWN,
    9: ActionConstants.DOUBLE_DOWN,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  9: {
    2: ActionConstants.HIT,
    3: ActionConstants.DOUBLE_DOWN,
    4: ActionConstants.DOUBLE_DOWN,
    5: ActionConstants.DOUBLE_DOWN,
    6: ActionConstants.DOUBLE_DOWN,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  8: {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.HIT,
    5: ActionConstants.HIT,
    6: ActionConstants.HIT,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  7: {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.HIT,
    5: ActionConstants.HIT,
    6: ActionConstants.HIT,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  6: {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.HIT,
    5: ActionConstants.HIT,
    6: ActionConstants.HIT,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
  5: {
    2: ActionConstants.HIT,
    3: ActionConstants.HIT,
    4: ActionConstants.HIT,
    5: ActionConstants.HIT,
    6: ActionConstants.HIT,
    7: ActionConstants.HIT,
    8: ActionConstants.HIT,
    9: ActionConstants.HIT,
    10: ActionConstants.HIT,
    A: ActionConstants.HIT,
  },
};
