import React from "react";

const StrategyTable: React.FC = () => {
  return (
    <>
      <table>
        <tbody>
          <tr>
            <td> </td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>10</td>
            <td>A</td>
          </tr>
          <tr>
            <td>17+</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
          </tr>
          <tr>
            <td>16</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>15</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>14</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>13</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>12</td>
            <td>H</td>
            <td>H</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>11</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>H</td>
          </tr>
          <tr>
            <td>10</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>9</td>
            <td>H</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>5-8</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>A 8-10</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
          </tr>
          <tr>
            <td>A, 7</td>
            <td>S</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>S</td>
            <td>S</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>A, 6</td>
            <td>H</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>A, 5</td>
            <td>H</td>
            <td>H</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>A, 4</td>
            <td>H</td>
            <td>H</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>A, 3</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>D</td>
            <td>D</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>A, 2</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>D</td>
            <td>D</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>A, A, 8, 8</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
          </tr>
          <tr>
            <td>10, 10</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
            <td>S</td>
          </tr>
          <tr>
            <td>9, 9</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>S</td>
            <td>SP</td>
            <td>SP</td>
            <td>S</td>
            <td>S</td>
          </tr>
          <tr>
            <td>7, 7</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>6, 6</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>5, 5</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>D</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>4, 4</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>SP</td>
            <td>SP</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>3, 3</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
          <tr>
            <td>2, 2</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>SP</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
            <td>H</td>
          </tr>
        </tbody>
      </table>
    </>
  );
};

export default StrategyTable;
