export const RESTART_GAME = "RESTART_GAME";

export const ADD_TO_BET = "ADD_TO_BET";

export const REMOVE_FROM_BET = "REMOVE_FROM_BET";

export const HIT = "HIT";

export const STAY = "STAY";

export const DOUBLE_DOWN = "DOUBLE_DOWN";

export const SPLIT = "SPLIT";

export const SPLIT_HIT = "SPLIT_HIT";

export const SPLIT_STAY = "SPLIT_STAY";

export const DEAL = "DEAL";

export const INCREASE_BANKROLL_RESET = "INCREASE_BANKROLL_RESET";

export const BLACKJACK_INCREASE_BANKROLL_RESET =
  "BLACKJACK_INCREASE_BANKROLL_RESET";

export const DECREASE_BANKROLL_RESET = "DECREASE_BANKROLL_RESET";

export const NO_CHANGE_BANKROLL_RESET = "NO_CHANGE_BANKROLL_RESET";

export const SPLIT_INCREASE_BANKROLL_RESET = "SPLIT_INCREASE_BANKROLL_RESET";

export const SPLIT_DECREASE_BANKROLL_RESET = "SPLIT_DECREASE_BANKROLL_RESET";

export const SPLIT_NO_CHANGE_BANKROLL_RESET = "SPLIT_NO_CHANGE_BANKROLL_RESET";
